### ISSUE TITLE
Can't get it to work (white page)

### ISSUE THREAD

**Issue by ParoTheParrot** [SSilence/markdownnotes#1]
I made the adjustments in .htaccess and index.html. data ist 767 (writable).
Tab name is "MarkdownNotes" (correct title in index.html), but the favicon isn't shown.

**Comment by ParoTheParrot** [comment]
No, sorry to say. Only a white page with the correct favicon and correct tab name.

**Comment by ParoTheParrot** [comment]
in the ''index.html''
``
<script type="text/javascript" src="runtime.ec2944dd8b20ec099bf3.js"></script><script type="text/javascript" src="polyfills.5be5f06196e92ccd0f54.js"></script><script type="text/javascript" src="scripts.1e4da2664bfc10d4a4a1.js"></script><script type="text/javascript" src="main.e4df251b4814e4c44403.js"></script></body>
``

**Comment by SSilence** [comment]
Do you use the apache server? Can you check the Apache logs? Does your Apache has the modrewrite module enabled? You can do this with ``a2enmod rewrite``

You can also use MarkdownNotes with docker: https://github.com/SSilence/markdownnotes#installation-using-docker

**Comment by georgesuba** [comment]
Hi, 
SSilence, thanks for this app. I wanted to try it for my own docs (cooking book) as I do use something php flat file wiki for my ICT documentation, however I hate to admit, I am getting white page as well. I followed your readme file, used apache with mod enabled of course and there is no error generated in docs.. as soon as I remove index.html to just check if it generate any sort of error, then it does. I cannot load the app on domain.com, sub.domain.com nor domain.com/markdownnotes - it all beehive in same manner. Permissions also set correctly. Any clues?

**Comment by ParoTheParrot** [comment]
Now I tried the markdownnotes-1.1! And it works like a charm :-)
