### ISSUE TITLE
How do the passwords work?

### ISSUE THREAD

**Issue by clupasq** [SSilence/markdownnotes#7]
Hey, this is a nice project and I'm glad I found it.

Could you please briefly explain how the password functionality works? I tried to use it but did not understand what "service" means, and how I can password protect one or more pages (if that's possible).

Thanks!

**Comment by SSilence** [comment]
Thanks a lot for using markdownnotes and asking. The password manager is just a simple one. In "service"-field I enter the website which is the username and password for. service is just a simple text field. I have two twitter accounts so I have two entries with "twitter" as service.

The passwords will be saved in a file on webserver. Before saving them they will be encrypted with AES. I do the encryption twice with two different AES libraries (when one has a security issue the second one is the fallback). The passwords will be only encrypted in browser in memory. I additionally encrypt every single password and just decrypt it when "copy" button was pressed or you showing it. A memory dump will not contain all passwords in clear text.

I hope this helps.

Best regards
 Tobi

**Comment by clupasq** [comment]
OK, thanks for the explanation! :+1: 

Now I realize it's a Password Manager.
I thought it was about protecting pages with passwords.
